package com.leancloud_text.SQL;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leancloud_text.SQL.UnreadMessage;

import com.leancloud_text.SQL.UnreadMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig unreadMessageDaoConfig;

    private final UnreadMessageDao unreadMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        unreadMessageDaoConfig = daoConfigMap.get(UnreadMessageDao.class).clone();
        unreadMessageDaoConfig.initIdentityScope(type);

        unreadMessageDao = new UnreadMessageDao(unreadMessageDaoConfig, this);

        registerDao(UnreadMessage.class, unreadMessageDao);
    }
    
    public void clear() {
        unreadMessageDaoConfig.clearIdentityScope();
    }

    public UnreadMessageDao getUnreadMessageDao() {
        return unreadMessageDao;
    }

}
