package com.leancloud_text.SQL;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leancloud_text.SQL.Passers;
import com.leancloud_text.SQL.UnreadMessage;

import com.leancloud_text.SQL.PassersDao;
import com.leancloud_text.SQL.UnreadMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig passersDaoConfig;
    private final DaoConfig unreadMessageDaoConfig;

    private final PassersDao passersDao;
    private final UnreadMessageDao unreadMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        passersDaoConfig = daoConfigMap.get(PassersDao.class).clone();
        passersDaoConfig.initIdentityScope(type);

        unreadMessageDaoConfig = daoConfigMap.get(UnreadMessageDao.class).clone();
        unreadMessageDaoConfig.initIdentityScope(type);

        passersDao = new PassersDao(passersDaoConfig, this);
        unreadMessageDao = new UnreadMessageDao(unreadMessageDaoConfig, this);

        registerDao(Passers.class, passersDao);
        registerDao(UnreadMessage.class, unreadMessageDao);
    }
    
    public void clear() {
        passersDaoConfig.clearIdentityScope();
        unreadMessageDaoConfig.clearIdentityScope();
    }

    public PassersDao getPassersDao() {
        return passersDao;
    }

    public UnreadMessageDao getUnreadMessageDao() {
        return unreadMessageDao;
    }

}
