package com.leancloud_text.SQL;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leancloud_text.SQL.Dialogue;
import com.leancloud_text.SQL.TalkList;
import com.leancloud_text.SQL.Passers;

import com.leancloud_text.SQL.DialogueDao;
import com.leancloud_text.SQL.TalkListDao;
import com.leancloud_text.SQL.PassersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dialogueDaoConfig;
    private final DaoConfig talkListDaoConfig;
    private final DaoConfig passersDaoConfig;

    private final DialogueDao dialogueDao;
    private final TalkListDao talkListDao;
    private final PassersDao passersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dialogueDaoConfig = daoConfigMap.get(DialogueDao.class).clone();
        dialogueDaoConfig.initIdentityScope(type);

        talkListDaoConfig = daoConfigMap.get(TalkListDao.class).clone();
        talkListDaoConfig.initIdentityScope(type);

        passersDaoConfig = daoConfigMap.get(PassersDao.class).clone();
        passersDaoConfig.initIdentityScope(type);

        dialogueDao = new DialogueDao(dialogueDaoConfig, this);
        talkListDao = new TalkListDao(talkListDaoConfig, this);
        passersDao = new PassersDao(passersDaoConfig, this);

        registerDao(Dialogue.class, dialogueDao);
        registerDao(TalkList.class, talkListDao);
        registerDao(Passers.class, passersDao);
    }
    
    public void clear() {
        dialogueDaoConfig.clearIdentityScope();
        talkListDaoConfig.clearIdentityScope();
        passersDaoConfig.clearIdentityScope();
    }

    public DialogueDao getDialogueDao() {
        return dialogueDao;
    }

    public TalkListDao getTalkListDao() {
        return talkListDao;
    }

    public PassersDao getPassersDao() {
        return passersDao;
    }

}
