package com.leancloud_text.SQL;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DIALOGUE".
 */
@Entity
public class Dialogue {

    @Id(autoincrement = true)
    private Long id;
    private String conversation_id;
    private String conversation_name;
    private String From_ID;
    private String content;
    private java.util.Date upadte_time;
    private Boolean isRead;

    @Generated
    public Dialogue() {
    }

    public Dialogue(Long id) {
        this.id = id;
    }

    @Generated
    public Dialogue(Long id, String conversation_id, String conversation_name, String From_ID, String content, java.util.Date upadte_time, Boolean isRead) {
        this.id = id;
        this.conversation_id = conversation_id;
        this.conversation_name = conversation_name;
        this.From_ID = From_ID;
        this.content = content;
        this.upadte_time = upadte_time;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getConversation_id() {
        return conversation_id;
    }

    public void setConversation_id(String conversation_id) {
        this.conversation_id = conversation_id;
    }

    public String getConversation_name() {
        return conversation_name;
    }

    public void setConversation_name(String conversation_name) {
        this.conversation_name = conversation_name;
    }

    public String getFrom_ID() {
        return From_ID;
    }

    public void setFrom_ID(String From_ID) {
        this.From_ID = From_ID;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getUpadte_time() {
        return upadte_time;
    }

    public void setUpadte_time(java.util.Date upadte_time) {
        this.upadte_time = upadte_time;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
