package com.leancloud_text.SQL;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PASSERS".
 */
@Entity
public class Passers {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String UserObjectId;

    @NotNull
    private String name;
    private byte[] UserImageBy;
    private String UserImage;
    private Boolean isfollow;

    @Generated
    public Passers() {
    }

    public Passers(Long id) {
        this.id = id;
    }

    @Generated
    public Passers(Long id, String UserObjectId, String name, byte[] UserImageBy, String UserImage, Boolean isfollow) {
        this.id = id;
        this.UserObjectId = UserObjectId;
        this.name = name;
        this.UserImageBy = UserImageBy;
        this.UserImage = UserImage;
        this.isfollow = isfollow;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUserObjectId() {
        return UserObjectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserObjectId(@NotNull String UserObjectId) {
        this.UserObjectId = UserObjectId;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public byte[] getUserImageBy() {
        return UserImageBy;
    }

    public void setUserImageBy(byte[] UserImageBy) {
        this.UserImageBy = UserImageBy;
    }

    public String getUserImage() {
        return UserImage;
    }

    public void setUserImage(String UserImage) {
        this.UserImage = UserImage;
    }

    public Boolean getIsfollow() {
        return isfollow;
    }

    public void setIsfollow(Boolean isfollow) {
        this.isfollow = isfollow;
    }

}
