package com.leancloud_text.SQL;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TALK_LIST".
 */
@Entity
public class TalkList {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String conversation_id;
    private String members;

    @NotNull
    private String conversation_name;
    private String unreadCount;
    private String content;
    private java.util.Date upadte_time;
    private Boolean isRead;

    @Generated
    public TalkList() {
    }

    public TalkList(Long id) {
        this.id = id;
    }

    @Generated
    public TalkList(Long id, String conversation_id, String members, String conversation_name, String unreadCount, String content, java.util.Date upadte_time, Boolean isRead) {
        this.id = id;
        this.conversation_id = conversation_id;
        this.members = members;
        this.conversation_name = conversation_name;
        this.unreadCount = unreadCount;
        this.content = content;
        this.upadte_time = upadte_time;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getConversation_id() {
        return conversation_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setConversation_id(@NotNull String conversation_id) {
        this.conversation_id = conversation_id;
    }

    public String getMembers() {
        return members;
    }

    public void setMembers(String members) {
        this.members = members;
    }

    @NotNull
    public String getConversation_name() {
        return conversation_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setConversation_name(@NotNull String conversation_name) {
        this.conversation_name = conversation_name;
    }

    public String getUnreadCount() {
        return unreadCount;
    }

    public void setUnreadCount(String unreadCount) {
        this.unreadCount = unreadCount;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getUpadte_time() {
        return upadte_time;
    }

    public void setUpadte_time(java.util.Date upadte_time) {
        this.upadte_time = upadte_time;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
