package com.leancloud_text.SQL;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "UNREAD_MESSAGE".
 */
@Entity
public class UnreadMessage {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String conversation_id;
    private String members;

    @NotNull
    private String name;
    private String unreadCount;
    private String content;
    private java.util.Date upadte_time;

    @Generated
    public UnreadMessage() {
    }

    public UnreadMessage(Long id) {
        this.id = id;
    }

    @Generated
    public UnreadMessage(Long id, String conversation_id, String members, String name, String unreadCount, String content, java.util.Date upadte_time) {
        this.id = id;
        this.conversation_id = conversation_id;
        this.members = members;
        this.name = name;
        this.unreadCount = unreadCount;
        this.content = content;
        this.upadte_time = upadte_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getConversation_id() {
        return conversation_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setConversation_id(@NotNull String conversation_id) {
        this.conversation_id = conversation_id;
    }

    public String getMembers() {
        return members;
    }

    public void setMembers(String members) {
        this.members = members;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getUnreadCount() {
        return unreadCount;
    }

    public void setUnreadCount(String unreadCount) {
        this.unreadCount = unreadCount;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getUpadte_time() {
        return upadte_time;
    }

    public void setUpadte_time(java.util.Date upadte_time) {
        this.upadte_time = upadte_time;
    }

}
